//Next
import Head from 'next/head'
import Image from 'next/image';
import { useRouter } from 'next/router';

//React
import React, { useState, useEffect } from 'react'

//Material UI
import MuiAlert, { AlertProps } from '@mui/material/Alert';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import { IconButton } from '@mui/material';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

//Material UI - icons
import PersonPinTwoToneIcon from '@mui/icons-material/PersonPinTwoTone';
import LockTwoToneIcon from '@mui/icons-material/LockTwoTone';
import AccountTreeTwoToneIcon from '@mui/icons-material/AccountTreeTwoTone';

//Components
import SideBar from '@/components/global/Sidebar';
import Profile from '@/components/student/Profile';
import Projects from '@/components/student/Projects';
import UpdatePassword from '@/components/auth/UpdatePassword';

//Alert
const Alert = React.forwardRef<HTMLDivElement, AlertProps>(function Alert(
  props,
  ref,
) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}

export default function Dashboard() {
    //router
    const router = useRouter()

    const [value, setValue] = useState(0);

    const handleChange = (event: React.SyntheticEvent, newValue: number) => {
      setValue(newValue);
    };

    return (
      <>
        <Head>
          <title>Servicio Social - ITESM</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=''>
            <SideBar/>
            <div className='lg:w-[calc(100%-176px)] min-h-screen bg-light dark:bg-dark lg:left-44 relative pt-10 p-5 md:p-10 xl:p-20'>
              <div className='mb-4'>
                <h2 className='title text-black dark:text-white'>Tu perfil</h2>
              </div>

              <div className='rounded-xl bg-lightAlt dark:bg-darkAlt p-5'>
                {/* tabs */}
                <Tabs
                  value={value}
                  onChange={handleChange}
                  aria-label="icon position tabs example"
                  textColor="primary"
                  indicatorColor="primary"
                  
                >
                  <Tab className='text-black dark:text-white opacity-70 hover:opacity-100' style={{opacity: value === 0 ? 1 : 0.7}} icon={<PersonPinTwoToneIcon />} iconPosition="start" label="Perfil" />
                  <Tab className='text-black dark:text-white opacity-70 hover:opacity-100' style={{opacity: value === 1 ? 1 : 0.7}} icon={<AccountTreeTwoToneIcon />} iconPosition="start" label="Proyectos" />
                  <Tab className='text-black dark:text-white opacity-70 hover:opacity-100' style={{opacity: value === 2 ? 1 : 0.7}} icon={<LockTwoToneIcon />} iconPosition="start" label="Cambiar Contraseña" />
                </Tabs>

                {/* tab panel */}
                <TabPanel value={value} index={0}>
                  <Profile/>
                </TabPanel>
                <TabPanel value={value} index={1}>
                  <Projects/>
                </TabPanel>
                <TabPanel value={value} index={2}>
                  <UpdatePassword/>
                </TabPanel>
              </div>
            </div>
        </main>
      </>
    )
}
