//Next
import Head from 'next/head'
import Image from 'next/image';
import { useRouter } from 'next/router';

//React
import React, { useState, useEffect } from 'react'

//Material UI
import Snackbar from '@mui/material/Snackbar';
import { Theme, useTheme } from '@mui/material/styles';
import MuiAlert, { AlertProps } from '@mui/material/Alert';
import { IconButton, Collapse, Tooltip } from '@mui/material';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import Chip from '@mui/material/Chip';
import Box from '@mui/material/Box';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';

//Material UI - icons
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import CancelRoundedIcon from '@mui/icons-material/CancelRounded';
import DashboardCustomizeRoundedIcon from '@mui/icons-material/DashboardCustomizeRounded';
import { CreateRounded, DeleteRounded } from '@mui/icons-material';
import Groups2RoundedIcon from '@mui/icons-material/Groups2Rounded';

//CSS
import styles from '@/styles/Home.module.css'

//Components
import SideBar from '@/components/global/Sidebar';
import { TransparentInput } from '@/components/global/Select';

//Context
import { useAuth } from '@/context/AuthContext';
import { useProjects } from '@/context/ProjectsContext';

//data
import carreras from '@/utils/constants/carreras';
import claves from '@/utils/constants/claves';
import duration from '@/utils/constants/duration';
import hours from '@/utils/constants/hours';
import modalities from '@/utils/constants/modalities';
import inscripcion from '@/utils/constants/inscripcion';

//interfaces
import Project from '@/utils/interfaces/Project.interface';


//Alert
const Alert = React.forwardRef<HTMLDivElement, AlertProps>(function Alert(
  props,
  ref,
) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});


function getStyles(name: string, personName: readonly string[], theme: Theme) {
  return {
    fontWeight:
      personName.indexOf(name) === -1
        ? theme.typography.fontWeightRegular
        : theme.typography.fontWeightMedium,
  };
}

const ITEM_HEIGHT = 48;
const ITEM_PADDING_TOP = 8;
const MenuProps = {
  PaperProps: {
    style: {
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
      width: 250,
    },
  },
};



export default function Students() {
    //context
    const { user } = useAuth()
    const selectedProject:Project = useProjects().selectedProject

    //Material UI
    const theme = useTheme();

    //router
    const router = useRouter()

    //useState
    const [projectsList, setProjectsList] = useState<Array<Project>>([])

    //useState - formData
    const [formData, setFormData] = useState({
      name: "",
      key: "",
      group: "",
      crn: "",
      duration: "",
      hours: "",
      inscription: "",
      availability: "",
      modality: "",
      location: "",
    })
    const [carrerasList, setCarrerasList] = useState<string[]>([]);

    //useState - alert open
    const [utils, setUtils] = useState({
      open: false,
      message: "",
      severity: "error",
      collapse: false
    })


    //useEffect
    useEffect(() => {
      //console.log(user)
      /* if(user) {
        if(projects.length !== 0) {
          setProjectsList(projects)
        } else {
          fecthProjects()
        }
      } */
    },[])



    return (
      <>
        <Head>
          <title>Servicio Social - ITESM</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=''>
            <SideBar/>
            <div className='lg:w-[calc(100%-176px)] min-h-screen bg-light dark:bg-dark lg:left-44 relative p-4 md:p-10 pb-20'>
                {/* header */} 
                <div className='flex justify-between items-center max-w-5xl m-auto mt-10'>
                    <h2 className='title text-dark dark:text-light flex-1'>Alumnos solicitantes</h2>
                    {selectedProject.name}
                </div>

            </div>
        </main>
      </>
    )
}
